export const MAJOR_ARCANA = [
    { id: "0", name: "愚者", englishName: "The Fool", description: "新的開始、冒險、純真、自發、自由精神。" },
    { id: "1", name: "魔術師", englishName: "The Magician", description: "創造力、行動、轉化、資源豐富、意志力。" },
    { id: "2", name: "女祭司", englishName: "The High Priestess", description: "直覺、潛意識、神祕、內在知曉、靜默。" },
    { id: "3", name: "皇后", englishName: "The Empress", description: "豐盛、母性、感官享受、自然、孕育。" },
    { id: "4", name: "皇帝", englishName: "The Emperor", description: "權威、結構、基礎、控制、穩定。" },
    { id: "5", name: "教皇", englishName: "The Hierophant", description: "傳統、精神引導、體制、一致性、精神教導。" },
    { id: "6", name: "戀人", englishName: "The Lovers", description: "選擇、合一、價值觀、合作、吸引力。" },
    { id: "7", name: "戰車", englishName: "The Chariot", description: "勝利、意志、控制強大的力量、決心、紀律。" },
    { id: "8", name: "力量", englishName: "Strength", description: "內在力量、勇氣、耐心、慈悲、韌性。" },
    { id: "9", name: "隱士", englishName: "The Hermit", description: "尋求真理、孤獨、內省、引導、自我反省。" },
    { id: "10", name: "命運之輪", englishName: "Wheel of Fortune", description: "命運、週期、轉折點、好運、業力。" },
    { id: "11", name: "正義", englishName: "Justice", description: "公平、平衡、真理、因果、公正。" },
    { id: "12", name: "倒吊人", englishName: "The Hanged Man", description: "不同的視角、暫停、犧牲、放手、等待。" },
    { id: "13", name: "死亡", englishName: "Death", description: "結束、轉變、過渡、重生、放手過去。" },
    { id: "14", name: "節制", englishName: "Temperance", description: "平衡、適度、耐心、融合、調和。" },
    { id: "15", name: "惡魔", englishName: "The Devil", description: "束縛、成癮、物質主義、陰影自我、恐懼。" },
    { id: "16", name: "高塔", englishName: "The Tower", description: "突如其來的劇變、啟示、混亂、覺醒、基礎崩塌。" },
    { id: "17", name: "星星", englishName: "The Star", description: "希望、信念、更新、靈感、寧靜。" },
    { id: "18", name: "月亮", englishName: "The Moon", description: "幻象、恐懼、焦慮、潛意識、直覺、神祕。" },
    { id: "19", name: "太陽", englishName: "The Sun", description: "成功、歡樂、活力、純潔、熱情、清晰。" },
    { id: "20", name: "審判", englishName: "Judgement", description: "召喚、重生、赦免、覺醒、決定。" },
    { id: "21", name: "世界", englishName: "The World", description: "完成、整合、成就、旅程結束、整體。" }
];
